#define TEST
/**
 * @file main_test.c
 * @brief Correctness test for the masked Knuth-Yao sampler.
 *
 * The masked sampler is compared against the unmasked evaluation of the same
 * circuit, which serves as the reference: for identical input randomness, both
 * must return identical samples. The parameter set is selected at compile time
 * (see masked.h).
 *
 * - FRODO parameter sets: the input space (PRECISION magnitude bits + 1 sign
 *   bit = 16 bits) is small enough to be tested EXHAUSTIVELY. Every possible
 *   input is enumerated, 32 per batch (bitsliced lanes).
 * - HAWK parameter sets: the input space (79 bits) is too large, so we test
 *   2^15 pseudo-random inputs instead, generated by a fixed-seed xorshift so
 *   that runs are reproducible.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "hal.h"
#include "masked.h"
#include "ky_samplers.h"
#include "unmasked_ky_samplers.h"
#include "gadgets_masked.h"

/* ------------------------------------------------------------------------- */
/* Parameter selection                                                        */
/* ------------------------------------------------------------------------- */
#if defined(FRODO_640)
    #define PARAM_NAME "test_frodo_640"
    #define IS_HAWK 0
    #define PRECISION 15
#elif defined(FRODO_976)
    #define PARAM_NAME "test_frodo_976"
    #define IS_HAWK 0
    #define PRECISION 15
#elif defined(FRODO_1344)
    #define PARAM_NAME "test_frodo_1344"
    #define IS_HAWK 0
    #define PRECISION 15
#elif defined(HAWK_256_T0)
    #define PARAM_NAME "test_hawk_256_t0"
    #define IS_HAWK 1
    #define PRECISION 78
#elif defined(HAWK_256_T1)
    #define PARAM_NAME "test_hawk_256_t1"
    #define IS_HAWK 1
    #define PRECISION 78
#elif defined(HAWK_512_T0)
    #define PARAM_NAME "test_hawk_512_t0"
    #define IS_HAWK 1
    #define PRECISION 78
#elif defined(HAWK_512_T1)
    #define PARAM_NAME "test_hawk_512_t1"
    #define IS_HAWK 1
    #define PRECISION 78
#elif defined(HAWK_1024_T0)
    #define PARAM_NAME "test_hawk_1024_t0"
    #define IS_HAWK 1
    #define PRECISION 78
#elif defined(HAWK_1024_T1)
    #define PARAM_NAME "test_hawk_1024_t1"
    #define IS_HAWK 1
    #define PRECISION 78
#else
    #error "Please define a parameter set (e.g., FRODO_640 or HAWK_512_T0)"
#endif

#define INPUT_BITS (PRECISION + 1)   /* magnitude bits + sign bit             */
#define SIGN_PLANE (PRECISION)       /* index of the sign bit-plane           */
#define MAG_BITS   (OUTPUT_SIZE - 1) /* magnitude bits in the circuit output  */

/* Circuit symbols are derived from the parameter set through masked.h's Z()  */
#define MASKED_CIRCUIT   Z(masked_ky_sampler_)
#define UNMASKED_CIRCUIT Z(unmasked_ky_sampler_)

#define MAX_REPORTED_FAILS 10

/* ------------------------------------------------------------------------- */
/* Input generation                                                           */
/* ------------------------------------------------------------------------- */
#if IS_HAWK
/* 2^15 random inputs, 32 lanes per batch */
#define NUM_BATCHES ((1u << 15) / 32)

/* Fixed-seed xorshift32: reproducible across runs, no TRNG dependency */
static uint32_t prng_state = 0xC0FFEE42u;
static uint32_t prng32(void) {
    uint32_t x = prng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    return prng_state = x;
}

/* Each bit-plane filled with a random word: lane k of the batch receives a
 * uniform INPUT_BITS-bit input (bit j of input k = bit k of plane j). */
static void fill_input_planes(uint32_t planes[INPUT_BITS], uint32_t batch) {
    (void)batch;
    for (int bit = 0; bit < INPUT_BITS; bit++) {
        planes[bit] = prng32();
    }
}
#else
/* Exhaustive enumeration: 2^INPUT_BITS inputs, 32 lanes per batch */
#define NUM_BATCHES ((1u << INPUT_BITS) / 32)

/* Lane l of batch b receives the input value v = 32*b + l */
static void fill_input_planes(uint32_t planes[INPUT_BITS], uint32_t batch) {
    for (int bit = 0; bit < INPUT_BITS; bit++) {
        planes[bit] = 0;
        for (int lane = 0; lane < 32; lane++) {
            uint32_t v = 32u * batch + (uint32_t)lane;
            planes[bit] |= ((v >> bit) & 1u) << lane;
        }
    }
}
#endif

/* Extract bit `lane` of each of the first `nbits` planes as an integer */
static uint32_t gather_lane(const uint32_t *planes, int nbits, int lane) {
    uint32_t v = 0;
    for (int bit = 0; bit < nbits; bit++) {
        v |= ((planes[bit] >> lane) & 1u) << bit;
    }
    return v;
}

/* ------------------------------------------------------------------------- */
/* Test                                                                       */
/* ------------------------------------------------------------------------- */
int main(void) {
    hal_setup();
    hal_send_str("START KNUTH-YAO CORRECTNESS TEST (" PARAM_NAME ")");

    char out_buf[128];
    uint32_t total_errors = 0;

    for (uint32_t b = 0; b < NUM_BATCHES; b++) {
        uint32_t planes[INPUT_BITS];
        fill_input_planes(planes, b);

        /* --- Reference: unmasked circuit (magnitude) + scalar sign --- */
        uint32_t ref_planes[OUTPUT_SIZE] = {0};
        UNMASKED_CIRCUIT(ref_planes, planes);

        /* --- Masked run on the same inputs --- */
        uint32_t masked_in[INPUT_BITS * NSHARES];
        for (int bit = 0; bit < INPUT_BITS; bit++) {
            mask(masked_in + bit * NSHARES, planes[bit]);
        }

        uint32_t masked_out[OUTPUT_SIZE * NSHARES] = {0};
        masked_sampler(MASKED_CIRCUIT, masked_out, masked_in, PRECISION);

        uint32_t out_planes[OUTPUT_SIZE];
        for (int i = 0; i < OUTPUT_SIZE; i++) {
            unmask(&out_planes[i], masked_out + i * NSHARES);
        }

        /* --- Lane-by-lane comparison --- */
        for (int lane = 0; lane < 32; lane++) {
            /* Expected value: unmasked magnitude, sign applied in plain C */
            uint32_t mag  = gather_lane(ref_planes, MAG_BITS, lane);
            uint32_t sign = (planes[SIGN_PLANE] >> lane) & 1u;
            int32_t  exp  = sign ? -(int32_t)mag : (int32_t)mag;

            /* Obtained value: OUTPUT_SIZE-bit two's complement, sign-extended */
            uint32_t raw = gather_lane(out_planes, OUTPUT_SIZE, lane);
            if (raw & (1u << (OUTPUT_SIZE - 1))) {
                raw |= ~((1u << OUTPUT_SIZE) - 1u);
            }
            int32_t got = (int32_t)raw;

            if (got != exp) {
                if (total_errors < MAX_REPORTED_FAILS) {
                    sprintf(out_buf, "FAIL: Batch %lu Lane %d | Exp: %ld | Got: %ld",
                            (unsigned long)b, lane, (long)exp, (long)got);
                    hal_send_str(out_buf);
                }
                total_errors++;
            }
        }
    }

    if (total_errors == 0) {
        hal_send_str("SUCCESS: MASKED AND UNMASKED SAMPLERS MATCH");
    } else {
        sprintf(out_buf, "FAILED WITH %lu ERRORS", (unsigned long)total_errors);
        hal_send_str(out_buf);
    }

    hal_send_str("EOF");
    return 0;
}
