import sys
import argparse
from collections import Counter

# HAWK 256 T0 Specification (RCDT)
HAWK256_T0_RCDT = [
    0x26B871FBD58485D45050, 0x07C054114F1DC2FA7AC9, 0x00A242F74ADDA0B5AE61,
    0x0005252E2152AB5D758B, 0x00000FDE62196C1718FC, 0x000000127325DDF8CEBA,
    0x0000000008100822C548, 0x00000000000152A6E9AE, 0x0000000000000014DA4A,
    0x0000000000000000007B
]

PRECISION = 78

def get_hawk_half_pmf():
    """Converts the Cumulative Distribution Table to an exact half-Gaussian PMF."""
    pmf = []
    # P(|X| = 0) = Total Mass (2^precision) - P(|X| >= 1)
    pmf.append((1 << PRECISION) - HAWK256_T0_RCDT[0])
    
    # P(|X| = i) = P(|X| >= i) - P(|X| >= i+1)
    for i in range(len(HAWK256_T0_RCDT) - 1):
        pmf.append(HAWK256_T0_RCDT[i] - HAWK256_T0_RCDT[i+1])
        
    # P(|X| = max)
    pmf.append(HAWK256_T0_RCDT[-1])
    return pmf

def main():
    parser = argparse.ArgumentParser(description="Verify stochastic distribution of HAWK bitsliced sampler.")
    parser.add_argument("filename", help="Text file containing the serial output integers.")
    args = parser.parse_args()

    try:
        with open(args.filename, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: File '{args.filename}' not found.")
        return

    samples = []
    for line in lines:
        line = line.strip()
        try:
            samples.append(int(line))
        except ValueError:
            pass

    total_samples = len(samples)
    if total_samples == 0:
        print("No valid integer samples found in the file.")
        return

    counts = Counter(samples)
    
    # Generate the exact mathematical half-Gaussian PMF
    half_pmf = get_hawk_half_pmf()
    total_mass = 1 << PRECISION
    
    print(f"Total parsed samples: {total_samples}")
    print("Note: Since 2^79 tests are impossible, Expected values are scaled stochastically.\n")
    
    header = f"{'Sample':>8} | {'Theoretical %':>15} | {'Expected':>12} | {'Observed':>12} | {'Diff':>8}"
    print(header)
    print("-" * len(header))

    max_val = len(half_pmf) - 1
    
    for val in range(-max_val, max_val + 1):
        # Base probability from the half-Gaussian
        base_prob = half_pmf[abs(val)] / total_mass
        
        # Split the probability mass for non-zero values due to the sign bit
        if val == 0:
            true_probability = base_prob
        else:
            true_probability = base_prob / 2.0
            
        # Scale to the number of samples generated by the board
        expected_scaled = true_probability * total_samples
        observed = counts.get(val, 0)
        diff = observed - expected_scaled
        
        print(f"{val:>8} | {true_probability * 100:>14.6f}% | {expected_scaled:>12.2f} | {observed:>12} | {diff:>+8.2f}")

    print("\n" + "-" * len(header))
    print("If differences are small (statistical noise), the sampler is correct.")

if __name__ == "__main__":
    main()